### ISSUE TITLE
Error loading plugin homebridge-LEDStrip

### ISSUE THREAD

**Issue by LukStankovic** [tgymnich/homebridge-LEDStrip#1]
Hi!
I've problem with pigpio at initialise. 

I really need homebridge plugin that works with pigpio. Do you know what is wrong? I tried also reinstalling pigpio in homebridge-LEDStrip folder.

Thank you!

![snimek obrazovky 2017-02-15 v 21 20 19](https://cloud.githubusercontent.com/assets/14925987/22993807/a7a2d1e8-f3c4-11e6-861c-5095aec9cf5d.png)

**Comment by tgymnich** [comment]
I sorry i cant help you with that i threw this plugin together a year ago. And didnt really use it afterwards. Did you use root to install pigpio?
